# baseURL = "https://your_domain.com/"
languageCode = "en"
defaultContentLanguage = "en"

title = "Links do Timot"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[author]
  name = "Timot"
  headline = "Todos os meus links aqui!"
  image = "timot.jpg" 

  links = [
    # { email = "mailto:hello@your_domain.com" },
    # { link = "https://link-to-some-website.com/" },
    { amazon = "https://www.amazon.es/hz/wishlist/ls/3DW3RDCI5SUC1?ref_=wl_share" },
    # { apple = "https://www.apple.com" },
    # { codepen = "https://codepen.io/username" },
    # { dev = "https://dev.to/username" },
    # { discord = "https://discord.gg/invitecode" },
    # { dribbble = "https://dribbble.com/username" },
    # { facebook = "https://facebook.com/username" },
    # { flickr = "https://www.flickr.com/photos/username/" },
    # { foursquare = "https://foursquare.com/username" },
    { github = "https://github.com/timotofcourse" },
    # { gitlab = "https://gitlab.com/username" },
    # { google = "https://www.google.com/" },
    # { instagram = "https://instagram.com/username" },
    # { keybase = "https://keybase.io/username" },
    # { kickstarter = "https://www.kickstarter.com/profile/username" },
    # { lastfm = "https://last.fm/user/username" },
    # { linkedin = "https://linkedin.com/in/username" },
    { mastodon = "https://mastodon.social/@timot_of_course" },
    # { medium = "https://medium.com/username" },
    # { microsoft = "https://www.microsoft.com/" },
    { patreon = "https://www.patreon.com/timot_of_course" },
    # { pinterest = "https://pinterest.com/username" },
    # { reddit = "https://reddit.com/user/username" },
    # { slack = "https://workspace.url/team/userid" },
    # { snapchat = "https://snapchat.com/add/username" },
    # { soundcloud = "https://soundcloud.com/username" },
    # { spotify = "https://spotify.com/user/username" },
    # { stack-exchange = "https://stackexchange.com/users/userid/username" },
    # { stack-overflow = "https://stackoverflow.com/users/userid/username" },
    { steam = "https://steamcommunity.com/id/timot_of_course/" },
    # { telegram = "https://t.me/username" },
    # { threads = "https://threads.com/username" },
    { tiktok = "https://www.patreon.com/timot_of_course" },
    # { tumblr = "https://username.tumblr.com" },
    { twitch = "https://twitch.tv/timot_of_course" },
    # { twitter = "https://twitter.com/username" },
    # { whatsapp = "https://wa.me/phone-number" },
    # { x = "https://x.com/username" },
    { youtube = "https://www.youtube.com/channel/UC2LkGjFhn0Oky9NckkNUimw"},
    { youtube = "https://www.youtube.com/@MuseudoTimot-fb3mm" },
    # { youtube = "https://youtube.com/username" },
    { link = "https://modrinth.com/user/Timot" },
    { link = "https://www.curseforge.com/members/timot/projects" },
    { link = "https://pixelfed.social/i/web/profile/583681200800987430" },
  ]

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"